name: 'actions-fixed-dependencies'
description: 'An action to verify that the (dev) dependencies in the package.json are fixed and not ranges.'
author: 'tangro'
inputs:
  check-dependencies:
    description: 'Set to "true" to check the dependencies'
    default: 'true'
  check-dev-dependencies:
    description: 'Set to "true" to check the devDependencies'
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
