name: 'actions-fixed-dependencies'
description: 'An action to verify that the (dev) dependencies in the package.json are fixed and not ranges.'
author: 'tangro'
inputs:
  check-dependencies:
    description: 'Set to "true" to check the dependencies'
    default: 'true'
  check-dev-dependencies:
    description: 'Set to "true" to check the devDependencies'
    default: 'true'
  post-comment:
    description: 'Set to "true" to post the results of the actions to the commit. Will only add a comment when the check failed.'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
